print ( "Em que ano você nasceu?")
nascimento = input()
nascimento = int(nascimento)
print ( "Para qual ano você quer saber sua idade ?")
saber = input ()
saber = int(saber)
print ("No ano", saber,"você tera",saber - nascimento,"anos!"  ) 
